### ISSUE TITLE
huggingface上的demo总是效果更好？

### ISSUE THREAD

**Issue by edisonblack55555** [SkyTNT/anime-segmentation#12]
不知道为什么，GitHub搭建的本地运行效果总是不如huggingface的demo，是哪个参数的问题吗？总是无法复现demo的效果

**Comment by SkyTNT** [comment]
用相同的图片试过吗？

**Comment by edisonblack55555** [comment]
有的，这是原图
![Screenshot_20230531_025858_com tencent mobileqq](https://github.com/SkyTNT/anime-segmentation/assets/117357308/0ebb0ee7-2ef2-4d6e-8763-6b62d166f502)
这是对比效果
demo：
![image](https://github.com/SkyTNT/anime-segmentation/assets/117357308/78337594-1f04-41bc-9ce3-2051cb12d8cd)
参数1024下
![image](https://github.com/SkyTNT/anime-segmentation/assets/117357308/32b18256-ecdd-4511-9dc5-1d4e97c1cef2)
参数1280下
![image](https://github.com/SkyTNT/anime-segmentation/assets/117357308/7d1ee75f-4381-4067-a632-991d24272b31)

**Comment by edisonblack55555** [comment]
补充对比：
![Screenshot_20230531_024135_com tencent mobileqq](https://github.com/SkyTNT/anime-segmentation/assets/117357308/e5ca9583-1b5f-4fcf-b21b-d2f5d9cbc145)
demo
![image](https://github.com/SkyTNT/anime-segmentation/assets/117357308/7dc6d4da-a28b-4cfa-8349-29d1369b480a)
1024
![image](https://github.com/SkyTNT/anime-segmentation/assets/117357308/12f5af64-91f2-46ac-b5ea-148f27663af2)
1280
![image](https://github.com/SkyTNT/anime-segmentation/assets/117357308/d33a3a07-548e-46fd-afbc-8f90eb40d1ae)

**Comment by SkyTNT** [comment]
忘记加.eval()了😂，提交更新了

**Comment by edisonblack55555** [comment]
> 忘记加.eval()了😂，提交更新了

非常感谢，问题完美解决
