### ISSUE TITLE
InSPyReNet

### ISSUE THREAD

**Issue by Zarxrax** [SkyTNT/anime-segmentation#7]
Is it possible to add support for InSPyReNet to the training code?
https://github.com/plemeri/inspyrenet

Their paper shows significant improvement from ISNet.

**Comment by SkyTNT** [comment]
Added it just now. But i have no time to train it.

**Comment by Zarxrax** [comment]
Thanks, I was able to train it for a few hours to test.
In train.py, I had to revert line 188 back to:
`strategy="ddp_find_unused_parameters_false" if opt.devices > 1 else None,`
Then the training worked.

I was not able to get export to onnx working.
But I could test through the app.py. So far it does not seem to be as good as the other models, but I will try some experiments to get a better result.
